### ISSUE TITLE
Is this plugin alive?

### ISSUE THREAD

**Issue by Aerendir** [bfiessinger/wppedia#49]
I'd like to know if this plugin is still alive or not.

**Comment by bfiessinger** [comment]
Hi @Aerendir,

I had to stop the active development due to a big internal project we had to build. That being said I have plans to continue the work on this plugin over the course of the next two months. However, I cannot give any exact dates at the moment.

**Comment by Aerendir** [comment]
Hi @bfiessinger ,
thank you very much for your reply...

Do you know if it may have any issues with the latest version of WordPress?

**Comment by bfiessinger** [comment]
We are running WPPedia on one of our websites on WordPress 5.9.2. As far as I know there are no known issues specifically to WordPress.

**Comment by Aerendir** [comment]
@bfiessinger ok, so it is not updated, but this is not a problem for the moment... I'll give it a try 💪
